# Generated by Django 4.2.4 on 2025-11-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('population_2024', models.BigIntegerField()),
                ('total_chws', models.IntegerField()),
                ('chws_per_10000', models.FloatField()),
                ('total_regions', models.IntegerField()),
                ('total_districts', models.IntegerField()),
                ('data_year', models.IntegerField()),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=150)),
                ('district_count', models.IntegerField()),
                ('region_number', models.IntegerField()),
                ('province', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=200)),
                ('chw_count', models.IntegerField()),
                ('population_est', models.BigIntegerField()),
                ('chws_per_10k', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.region')),
            ],
        ),
    ]
