# Generated by Django 4.2.4 on 2025-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chwfolder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country_name',
        ),
    ]
