// WHO Event data based on actual structure
export interface WHOEvent {
  id: string
  country: string
  lat: number
  lon: number
  disease: string
  grade: string
  eventType: string
  status: string
  description: string
  year: number
  reportDate: string
  cases?: number
  deaths?: number
}

export const whoEvents: WHOEvent[] = [
  {
    id: "1",
    country: "Malawi",
    lat: -13.9626,
    lon: 33.7741,
    disease: "Cholera",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description:
      "Cholera outbreak in Malawi. 3 confirmed cases, 23 suspected cases reported across Chitipa, Lilongwe, Balaka districts. Cross-border cases linked to Mozambique. OCV campaign planned. IMS on standby.",
    year: 2025,
    reportDate: "2025-12-19",
    cases: 26,
    deaths: 0,
  },
  {
    id: "2",
    country: "Mozambique",
    lat: -18.665695,
    lon: 35.529562,
    disease: "Cholera",
    grade: "Grade 3",
    eventType: "Outbreak",
    status: "Ongoing",
    description:
      "Ongoing cholera outbreak in Mozambique with cross-border transmission to Malawi. Cases reported in Lizinje area near border.",
    year: 2025,
    reportDate: "2025-12-18",
    cases: 145,
    deaths: 3,
  },
  {
    id: "3",
    country: "Nigeria",
    lat: 6.5244,
    lon: 3.3792,
    disease: "Cholera",
    grade: "Grade 3",
    eventType: "Outbreak",
    status: "Ongoing",
    description:
      "Severe cholera outbreak in Lagos and surrounding states. Multi-state outbreak with significant case load.",
    year: 2025,
    reportDate: "2025-12-15",
    cases: 2341,
    deaths: 67,
  },
  {
    id: "4",
    country: "Democratic Republic of the Congo",
    lat: -4.3217,
    lon: 15.3125,
    disease: "Mpox",
    grade: "Grade 3",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Ongoing mpox outbreak in DRC with sustained community transmission. Multiple provinces affected.",
    year: 2025,
    reportDate: "2025-12-20",
    cases: 8924,
    deaths: 156,
  },
  {
    id: "5",
    country: "Uganda",
    lat: 0.3476,
    lon: 32.5825,
    disease: "Mpox",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Mpox cases reported in Kampala and border districts. Contact tracing ongoing.",
    year: 2025,
    reportDate: "2025-12-17",
    cases: 234,
    deaths: 8,
  },
  {
    id: "6",
    country: "South Africa",
    lat: -30.5595,
    lon: 22.9375,
    disease: "Measles",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Measles outbreak in Western Cape province. Vaccination campaign intensified.",
    year: 2025,
    reportDate: "2025-12-14",
    cases: 456,
    deaths: 5,
  },
  {
    id: "7",
    country: "Ethiopia",
    lat: 9.145,
    lon: 40.4897,
    disease: "Cholera",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Cholera outbreak in Somali region. Humanitarian crisis contributing factor.",
    year: 2025,
    reportDate: "2025-12-16",
    cases: 567,
    deaths: 12,
  },
  {
    id: "8",
    country: "Kenya",
    lat: -1.286389,
    lon: 36.817223,
    disease: "Malaria",
    grade: "Grade 1",
    eventType: "Outbreak",
    status: "New",
    description: "Increased malaria transmission in coastal regions. Seasonal pattern observed.",
    year: 2025,
    reportDate: "2025-12-19",
    cases: 1234,
    deaths: 23,
  },
  {
    id: "9",
    country: "Ghana",
    lat: 5.6037,
    lon: -0.187,
    disease: "Yellow Fever",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Yellow fever outbreak in northern regions. Vaccination campaign deployed.",
    year: 2025,
    reportDate: "2025-12-13",
    cases: 89,
    deaths: 18,
  },
  {
    id: "10",
    country: "Somalia",
    lat: 2.0469,
    lon: 45.3182,
    disease: "Cholera",
    grade: "Grade 3",
    eventType: "Humanitarian Crisis",
    status: "Ongoing",
    description: "Severe cholera outbreak exacerbated by humanitarian crisis and flooding. Multiple regions affected.",
    year: 2025,
    reportDate: "2025-12-18",
    cases: 3456,
    deaths: 89,
  },
  {
    id: "11",
    country: "Zimbabwe",
    lat: -17.8252,
    lon: 31.0335,
    disease: "Typhoid",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Typhoid outbreak in Harare and surrounding areas. Water contamination suspected.",
    year: 2025,
    reportDate: "2025-12-12",
    cases: 234,
    deaths: 6,
  },
  {
    id: "12",
    country: "Tanzania",
    lat: -6.7924,
    lon: 39.2083,
    disease: "Cholera",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Cholera cases reported in Dar es Salaam and coastal regions.",
    year: 2025,
    reportDate: "2025-12-15",
    cases: 345,
    deaths: 9,
  },
  {
    id: "13",
    country: "Cameroon",
    lat: 3.848,
    lon: 11.5021,
    disease: "Cholera",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Cholera outbreak in Far North region. Cross-border surveillance enhanced.",
    year: 2025,
    reportDate: "2025-12-17",
    cases: 456,
    deaths: 14,
  },
  {
    id: "14",
    country: "Zambia",
    lat: -15.4167,
    lon: 28.2833,
    disease: "Cholera",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Cholera outbreak in Lusaka and Copperbelt provinces.",
    year: 2025,
    reportDate: "2025-12-14",
    cases: 678,
    deaths: 17,
  },
  {
    id: "15",
    country: "Niger",
    lat: 13.5127,
    lon: 2.1126,
    disease: "Meningitis",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "New",
    description: "Meningitis cases increasing in meningitis belt region. Seasonal pattern.",
    year: 2025,
    reportDate: "2025-12-19",
    cases: 123,
    deaths: 21,
  },
  {
    id: "16",
    country: "Rwanda",
    lat: -1.9403,
    lon: 29.8739,
    disease: "Marburg Virus",
    grade: "Grade 3",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Marburg virus outbreak. Contact tracing and isolation measures in place.",
    year: 2025,
    reportDate: "2025-12-11",
    cases: 12,
    deaths: 7,
  },
  {
    id: "17",
    country: "Burundi",
    lat: -3.3731,
    lon: 29.9189,
    disease: "Malaria",
    grade: "Grade 1",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Seasonal malaria increase in multiple provinces.",
    year: 2025,
    reportDate: "2025-12-16",
    cases: 2345,
    deaths: 34,
  },
  {
    id: "18",
    country: "Angola",
    lat: -8.8383,
    lon: 13.2344,
    disease: "Yellow Fever",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Yellow fever cases in Luanda province. Vaccination campaign ongoing.",
    year: 2025,
    reportDate: "2025-12-13",
    cases: 67,
    deaths: 12,
  },
  {
    id: "19",
    country: "Senegal",
    lat: 14.6928,
    lon: -17.4467,
    disease: "Dengue",
    grade: "Grade 1",
    eventType: "Outbreak",
    status: "New",
    description: "Dengue fever cases reported in Dakar. Vector control measures deployed.",
    year: 2025,
    reportDate: "2025-12-18",
    cases: 234,
    deaths: 2,
  },
  {
    id: "20",
    country: "Mali",
    lat: 12.6392,
    lon: -8.0029,
    disease: "Measles",
    grade: "Grade 2",
    eventType: "Outbreak",
    status: "Ongoing",
    description: "Measles outbreak in Bamako and surrounding regions. Vaccination coverage assessment ongoing.",
    year: 2025,
    reportDate: "2025-12-15",
    cases: 456,
    deaths: 11,
  },
]
