from django.db import models

class StarData(models.Model):
    key_on_table = models.CharField(max_length=5000, unique=True)
    n = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=5000, null=True, blank=True)
    level = models.CharField(max_length=5000, null=True, blank=True)
    year = models.CharField(max_length=5000, null=True, blank=True)
    start_date = models.CharField(max_length=5000, null=True, blank=True)
    end_date = models.CharField(max_length=5000, null=True, blank=True)
    subgroup_of_hazards = models.CharField(max_length=255, null=True, blank=True)
    main_type_of_hazard = models.CharField(max_length=255, null=True, blank=True)
    hazard = models.CharField(max_length=255, null=True, blank=True)
    health_consequences = models.CharField(max_length=5000, null=True, blank=True)
    scale = models.CharField(max_length=5000, null=True, blank=True)
    geographical_area = models.CharField(max_length=5000, null=True, blank=True)
    exposure = models.CharField(max_length=5000, null=True, blank=True)
    frequency = models.CharField(max_length=5000, null=True, blank=True)
    seasonality = models.CharField(max_length=5000, null=True, blank=True)
    jan = models.CharField(max_length=5000, null=True, blank=True)
    feb = models.CharField(max_length=5000, null=True, blank=True)
    mar = models.CharField(max_length=5000, null=True, blank=True)
    apr = models.CharField(max_length=5000, null=True, blank=True)
    may = models.CharField(max_length=5000, null=True, blank=True)
    jun = models.CharField(max_length=5000, null=True, blank=True)
    jul = models.CharField(max_length=5000, null=True, blank=True)
    aug = models.CharField(max_length=5000, null=True, blank=True)
    sep = models.CharField(max_length=5000, null=True, blank=True)
    oct = models.CharField(max_length=5000, null=True, blank=True)
    nov = models.CharField(max_length=5000, null=True, blank=True)
    dec = models.CharField(max_length=5000, null=True, blank=True)
    likelihood = models.CharField(max_length=5000, null=True, blank=True)
    severity = models.CharField(max_length=5000, null=True, blank=True)
    vulnerability = models.CharField(max_length=5000, null=True, blank=True)
    vulnerability_details = models.CharField(max_length=5000, null=True, blank=True)
    coping_capacity = models.CharField(max_length=5000, null=True, blank=True)
    coping_capacity_details = models.CharField(max_length=5000, null=True, blank=True)
    governance_and_resouces = models.CharField(max_length=5000, null=True, blank=True)
    health_sector_capacity = models.CharField(max_length=5000, null=True, blank=True)
    non_health_sector_capcity = models.CharField(max_length=5000, null=True, blank=True)
    commuty_capacity = models.CharField(max_length=5000, null=True, blank=True)
    resources = models.CharField(max_length=5000, null=True, blank=True)
    impact = models.CharField(max_length=5000, null=True, blank=True)
    confidence_level = models.CharField(max_length=5000, null=True, blank=True)
    risk_level = models.CharField(max_length=5000, null=True, blank=True)
    risk_level_number = models.CharField(max_length=5000, null=True, blank=True)
    status = models.CharField(max_length=5000, null=True, blank=True)